// The fortunes. Written for people in a hard stretch, especially a long job search.
// Rules: short, kind but not saccharine, a little wry, and no promises.
window.FORTUNES = [
  "A rejection is information, not a verdict.",
  "Rest counts as progress today.",
  "Someone out there is lucky they'll get to work with you.",
  "You don't have to feel ready to hit send.",
  "Silence from a company says more about their inbox than about you.",
  "One application today is still one more than zero.",
  "You are not behind. You are in the middle.",
  "The work you did last year still happened. Nobody can un-hire your skills.",
  "Your worth was never listed in the job description.",
  "Today's goal can be small enough to actually do.",
  "It's allowed to be hard. That doesn't mean you're doing it wrong.",
  "A 'no' closes one tab. You have other tabs.",
  "You have survived every Monday so far.",
  "The cover letter does not need to be perfect. It needs to be sent.",
  "Being tired of searching is not the same as being bad at it.",
  "You are more than your most recent email.",
  "Closing the laptop is also a decision. Sometimes the right one.",
  "Somebody is rooting for you and hasn't said it out loud yet.",
  "Motivation often shows up after you start, not before.",
  "The gap on your résumé is a chapter, not a blank page.",
  "You can be discouraged and still do the next small thing.",
  "A slow month is not a forecast.",
  "Your pace is not a flaw.",
  "Go outside. The job boards will still be there, unfortunately.",
  "You explained yourself well. They just had one seat.",
  "Doing it badly today beats doing it perfectly never.",
  "The right room will not need you to shrink.",
  "You've been brave more times this month than most people are all year.",
  "An unanswered application is not a conversation you lost.",
  "Eat something. Then decide how the day is going.",
  "Your skills did not expire while you were waiting.",
  "Ten minutes of effort still counts as showing up.",
  "It's fine to want this to be over. Keep going anyway, gently.",
  "You are allowed to be proud of things nobody paid you for.",
  "The interview you're replaying went better than you remember.",
  "Comparison is a bad recruiter. Don't take its calls.",
  "Not hearing back is their process, not your reflection.",
  "You've done harder things with less sleep.",
  "Take the afternoon off. Guilt is not a job requirement.",
  "A good day in a long search can be one honest attempt.",
  "Someone remembers working with you and smiles about it.",
  "The version of you who started this search would be impressed you're still at it.",
  "Ask for the referral. People like being asked more than you think.",
  "Your portfolio is not finished. Nobody's is. Send it.",
  "Being between things is still being somewhere.",
  "The algorithm skimmed you. A person hasn't read you yet.",
  "Small routines hold up big uncertain weeks.",
  "You don't owe anyone a cheerful update.",
  "Text a friend. Not about jobs. Just text a friend.",
  "Feeling stuck is a feeling, not a location.",
  "You only need one yes. The no's don't add up to anything.",
  "Careful, thoughtful people take longer to place. That's not a defect.",
  "The dread before starting is usually the worst part of the task.",
  "Whatever you managed today is today's amount. That's enough.",
  "You were good at this before anyone was grading it.",
  "A break is not quitting. It's how long things get finished.",
  "Your next coworkers don't know yet how much they'll like you.",
  "Drink some water. Reply to one thing. That's a plan.",
  "You're allowed to grieve the job you almost got.",
  "It's not too late, and you're not too much.",
  "Nobody's career is as tidy as their profile makes it look.",
  "Wanting good work is not asking for too much.",
  "The hard part isn't your talent. The hard part is the waiting.",
  "Be as kind to yourself as you'd be to a friend in the same spot.",
  "Tomorrow gets a fresh try. So does this afternoon.",
  "You can update the résumé later. First, a walk.",
  "A long search is a long search. It is not a long failure.",
  "Persistence looks boring from the inside. It still works on things.",
  "Whoever passed on you did not get the full picture. Their loss, genuinely.",
  "You are doing a hard thing without a schedule or a boss. Noted, and respected.",
  "Let today be average. Average days carry most of the load.",
  "The thing you're avoiding will take less time than the avoiding.",
  "You are still interesting on days you get nothing done.",
  "Somewhere, a hiring manager is hoping someone like you applies.",
  "Lower the bar for today. Step over it. Call it a win."
];

// A playful twist on the lucky numbers from the back of the slip.
window.LUCKY = [
  "Lucky interview day: Thursday",
  "Lucky numbers: 1 draft, 2 deep breaths, 3 p.m. walk",
  "Lucky snack: whatever is already in the fridge",
  "Lucky tab: the one you almost closed",
  "Lucky hour: the first one after coffee",
  "Lucky word: anyway",
  "Lucky numbers: 9, 5, and not a minute more",
  "Lucky outfit: the nice top, the comfy bottoms",
  "Lucky move: asking",
  "Lucky day off: today, if you need it",
  "Lucky numbers: 1 yes",
  "Lucky playlist: the embarrassing one",
  "Lucky follow-up: the one you keep putting off",
  "Lucky pen: any that still works",
  "Lucky season: the next one",
  "Lucky seat: by the window"
];
